### ISSUE TITLE
Data processing methods and parameter threshold and other related issues

### ISSUE THREAD

**Issue by Gxlhd614** [RHyde67/CEDAS#9]
Dear,
I am a student and interested in your work about the CEDAS, I want to get your KDDCup99 dataset and ask for the threshold of the Radius and MinimumClusterSize.Because I failed to reproduce your achievements may be used the wrong data preprocessing method of KDDCup99 dataset, I make many individual data points clustered on their own, so I can not get the right cluster quality.
Thanks for your help, I look forward to your reply.

**Comment by RHyde67** [comment]
I've had a dig through my archives and backups and found the actual code used for the paper (I think).
This used the pre-2015b version which had a minor bug which I have now corrected.
You should be able to get the same results using the version for later Matlab, but variable names, data structures etc are different. Extracting the info from Matlab's graph's is more complicated too.
The original work was completed using the pre-2015b version, so for testing the algorithm itself, this is probably the best version to use. The 2015 and later version using Matlab's new built-in graph structure is adapted from this.

Running 'runKDDCup.m' will produce all the graphs for you too.

'KDDCup_UseLatestCEDAS_Pre2015b.m' shows loading ta data (13),
changing categorical to numerical (18-28) and
normalising the data 0-1 (30-34).
This is all the pre-processing as far as i remember.
The parameters you asked about are set from line 40.

There may have been minor tweaks to the code since the paper for clarity. These may make slight differences in the results, but overall it is essentially the same.

[KDDCup99 Test.zip](https://github.com/RHyde67/CEDAS/files/6686549/KDDCup99.Test.zip)

**Comment by Gxlhd614** [comment]
Thank you very much! I found that I can't send email to your email address, because the address is wrong. Can I get your email? It is convenient for me to communicate with you better.

**Comment by RHyde67** [comment]
that's odd, I get emails from GitHub informing me of your communications. You may be using an old email from the paper from Lancaster University?
I am now at Coventry University, richard.hyde2@coventry.ac.uk
